# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request

on:
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      name: Download building script
      with:
        url: "https://github.com/SPRAVEDLIVO/RatReleaser/releases/latest/download/releaser.exe"
        target: "bruh/"
    - name: build
      id: build
      run: |
        bruh/releaser.exe --tag="yeahdefinately"